name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Linux executable
        run: npm run build-linux

      - name: Build MacOS x64 executable
        run: npm run build-macos-x64

      - name: Build MacOS arm64 executable
        run: npm run build-macos-arm64

      - name: Build Windows executable
        run: npm run build-windows

      - name: Create Release Entry
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}
            Contains Linux, MacOS x64 and Windows executables.
          draft: false
          prerelease: false

      - name: Upload Linux Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./a1-evo-acoustica-linux
          asset_name: a1-evo-acoustica-linux
          asset_content_type: application/octet-stream

      - name: Upload MacOS x64 Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./a1-evo-acoustica-macos-x64
          asset_name: a1-evo-acoustica-macos-x64
          asset_content_type: application/octet-stream

      - name: Upload MacOS arm64 Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./a1-evo-acoustica-macos-arm64
          asset_name: a1-evo-acoustica-macos-arm64
          asset_content_type: application/octet-stream

      - name: Upload Windows Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./a1-evo-acoustica-win.exe
          asset_name: a1-evo-acoustica-win.exe
          asset_content_type: application/vnd.microsoft.portable-executable
